package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

func main() {
	log.SetFlags(0)

	o := flag.String("o", "./internal/locales", "output directory for catalog.go and keys.go")
	flag.Parse()

	srcs := flag.Args()
	if len(srcs) == 0 {
		fmt.Fprintln(os.Stderr, "usage: go-text-yaml-gen -o <outdir> src...")
		fmt.Fprintln(os.Stderr, "  src: one or more directories to walk recursively for *.yaml files")
		fmt.Fprintln(os.Stderr, "flags:")
		flag.PrintDefaults()
		os.Exit(2)
	}

	merged, locales, keys, err := loadTranslations(srcs, os.Stderr)
	if err != nil {
		log.Fatal(err)
	}

	if err := os.MkdirAll(*o, 0o755); err != nil {
		log.Fatalf("creating output dir: %v", err)
	}
	if err := writeKeysFile(filepath.Join(*o, "keys.go"), keys); err != nil {
		log.Fatalf("writing keys.go: %v", err)
	}
	if err := writeCatalogFile(filepath.Join(*o, "catalog.go"), keys, locales, merged); err != nil {
		log.Fatalf("writing catalog.go: %v", err)
	}
}

// loadTranslations walks srcDirs, merges all *.yaml files, applies en fallbacks
// for missing locales (warnings written to warn), and returns the merged map plus
// sorted locales and keys.
func loadTranslations(srcDirs []string, warn io.Writer) (merged map[string]map[string]string, locales, keys []string, err error) {
	merged = make(map[string]map[string]string)

	for _, dir := range srcDirs {
		walkErr := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() || !strings.HasSuffix(path, ".yaml") {
				return nil
			}
			return parseYAML(path, merged)
		})
		if walkErr != nil {
			return nil, nil, nil, walkErr
		}
	}

	localeSet := make(map[string]bool)
	for _, locs := range merged {
		for loc := range locs {
			localeSet[loc] = true
		}
	}
	if !localeSet["en"] {
		return nil, nil, nil, fmt.Errorf(`locale "en" must be present in at least one translation entry`)
	}

	locales = sortedStringSet(localeSet)

	keys = make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		enVal := merged[key]["en"]
		for _, loc := range locales {
			if loc == "en" {
				continue
			}
			if _, ok := merged[key][loc]; !ok {
				fmt.Fprintf(warn, "WARN: key %q missing locale %q, falling back to en\n", key, loc)
				merged[key][loc] = enVal
			}
		}
	}

	return merged, locales, keys, nil
}

func parseYAML(path string, merged map[string]map[string]string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	var raw map[string]map[string]string
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("parsing %s: %w", path, err)
	}
	for key, locs := range raw {
		if _, exists := merged[key]; exists {
			return fmt.Errorf("duplicate key %q found (second occurrence in %s)", key, path)
		}
		merged[key] = locs
	}
	return nil
}

func sortedStringSet(s map[string]bool) []string {
	out := make([]string, 0, len(s))
	for k := range s {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		r, size := utf8.DecodeRuneInString(part)
		b.WriteRune(unicode.ToUpper(r))
		b.WriteString(part[size:])
	}
	return b.String()
}

func writeKeysFile(path string, keys []string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	maxLen := 0
	for _, key := range keys {
		if n := len("Key" + snakeToCamel(key)); n > maxLen {
			maxLen = n
		}
	}

	fmt.Fprintln(f, "// Code generated by gen-catalog. DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package locales")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "const (")
	for _, key := range keys {
		name := "Key" + snakeToCamel(key)
		pad := strings.Repeat(" ", maxLen-len(name)+1)
		fmt.Fprintf(f, "\t%s%s= %s\n", name, pad, strconv.Quote(key))
	}
	fmt.Fprintln(f, ")")

	return nil
}

func writeCatalogFile(path string, keys, locales []string, merged map[string]map[string]string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by gen-catalog. DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package locales")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, "\t\"golang.org/x/text/language\"")
	fmt.Fprintln(f, "\t\"golang.org/x/text/message\"")
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "func init() {")
	for _, locale := range locales {
		for _, key := range keys {
			fmt.Fprintf(f, "\tmessage.SetString(language.MustParse(%s), %s, %s)\n",
				strconv.Quote(locale),
				strconv.Quote(key),
				strconv.Quote(merged[key][locale]),
			)
		}
	}
	fmt.Fprintln(f, "}")

	return nil
}
