// Code generated by gen-catalog. DO NOT EDIT.

package locales

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

func init() {
	message.SetString(language.MustParse("en"), "cancel", "Cancel")
	message.SetString(language.MustParse("en"), "confirm_purchase", "Confirm purchase")
	message.SetString(language.MustParse("en"), "invalid_token", "Invalid token")
	message.SetString(language.MustParse("es"), "cancel", "Cancelar")
	message.SetString(language.MustParse("es"), "confirm_purchase", "Confirmar compra")
	message.SetString(language.MustParse("es"), "invalid_token", "Token inválido")
	message.SetString(language.MustParse("fr"), "cancel", "Annuler")
	message.SetString(language.MustParse("fr"), "confirm_purchase", "Confirmer l'achat")
	message.SetString(language.MustParse("fr"), "invalid_token", "Jeton invalide")
}
